import Head from 'next/head'
import { Inter } from 'next/font/google'
import Nav from '@/components/Nav'
import Header from '@/components/Header'
import { Container } from '@nextui-org/react'
import Footer from '@/components/Footer'
import About from '@/components/About'
import Gallery from '@/components/Gallery'
import SocialFeed from '@/components/SocialFeed'
import OurLocations from '@/components/OurLocations'
import OrderOnline from '@/components/OrderOnline'
import { Roboto } from 'next/font/google'

const serif = Inter({ subsets: ['latin'] })
// const serif = Roboto({
// 	subsets: ['latin'],
// 	weight: '300',
// })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Donut</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={`${serif.className} main`}>
				<Container md>
					<Nav />
					<Header />
					<Gallery />
					<About />
					<OrderOnline />
					<OurLocations />
					<SocialFeed />
					<Footer />
				</Container>
			</main>
		</>
	)
}
